name: Chocolatine

env:
  MIRROR_URL: git@github.com:EpitechPromo2028/B-MAT-200-COT-2-1-108trigo-pharel.ouindou.git
  EXECUTABLES: 108trigo

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

jobs:

  check_coding_style:
    name: Check Coding Style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Coding Style Check
        run: |
          check.sh $(pwd) $(pwd)
          cat coding-style-reports.log
          ! grep -q ERROR coding-style-reports.log

  check_program_compilation:
    name: Check Program Compilation
    needs: check_coding_style
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - name: Make
        run: make
      - name: Make Clean
        run: make clean
      - name: Check Executables
        run: |

  run_tests:
    name: Run Tests
    needs: check_program_compilation  
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    name: Push to Mirror
    needs: run_tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mirror Repository
        env:
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        run: |
          git remote set-url origin git@github.com:${{ github.repository }}.git
          git push --mirror ${{ env.MIRROR_URL }}