name: Chocolatine

on: 
  push:
    branches-ignore:
      - " ga-ignore-"
  pull_request:
    branches-ignore:
      - " ga-ignore-"

env:
  EXECUTABLE: setting_up
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: check coding-s
        uses: actions/checkout@v4.1.1

      - name: run c-s
        run: check.sh $(pwd) $(pwd)

      - name: display c-s
        run: cat coding-style-reports.log

      - name: vérif
        run: |
          if grep -q "." coding-style-reports.log
          then
            exit 1
          fi
