name: chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'

env:
  MIRROR_URL: "git@github.com:HKafuiEPI/miroir.git"
  EXECUTABLES: "202unsold"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4

      - name: run the coding style checker
        run: check.sh $(pwd) $(pwd)
      - name: ckeck the coding-style file
        run: |
          if [ -f coding-style-reports.log ]; then
             cat coding-style-reports.log
          else
             exit 1
          fi

  check_program_compilation:
     needs: check_coding_style
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker
     steps:
       - uses: actions/checkout@v4

       - name: compile my program
         run: make
         timeout-minutes: 2

       - name: clean my program
         run: make clean

       - name: ckeck binary
         run: |
           for x in $EXECUTABLES
           do
             if [ ! -f "$x" ]; then
                exit 1
             fi
           done

  run_tests:
    needs: [check_coding_style, check_program_compilation]
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4

      - name: compile my unit tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    needs: run_tests
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}