name: Chocolatine Workflow

on:
  push:
    branches-ignore:
      - ga-ignore-*
  pull_request:
    branches-ignore:
      - ga-ignore-*

env:
  MIRROR_URL: ${{ secrets.MIRROR_URL }}
  EXECUTABLES: "my_hunter"

jobs:
  check_coding_style:
    name: "Check Coding Style"
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Coding Style Checker
        run: check.sh $(pwd) $(pwd)

      - name: Display Errors
        if: failure()
        run: cat coding-style-reports.log && exit 1

  check_program_compilation:
    name: "Check Program Compilation"
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    needs: check_coding_style
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile Project
        run: timeout 120 make

      - name: Clean Compilation
        run: make clean

      - name: Verify Executables
        run: |
          for exe in $(echo $EXECUTABLES | tr ',' ' '); do
            if [ ! -x "$exe" ]; then
              echo "::error file=$exe::Executable $exe is missing or not executable"
              exit 1
            fi
          done