name: chocolatine

on: [push, pull_request]

jobs:
  coding-style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Run coding-style check
        run:  check.sh $(pwd) $(pwd)
      - name: verify if the file create is empty
        run: |
          if [ -s coding-style-reports.log ]; then
            cat "coding-style-reports.log"
            exit 1
          else
            cat "coding-style-reports.log"
          fi
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Make install
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build project
        run: timeout 120 make
      - name: Verify if  exist
        run: |
          if [ -f "mysh" ]; then
            echo "File exists."
          else
            echo "File doesn not exist."
            exit 1
          fi
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Make install
        run: sudo apt-get update && sudo apt-get install -y libcriterion-dev && sudo apt-get install -y build-essential
      - name: Build project
        run: make tests_run