name: learn-github-actions
run-name: ${{ github.actor }} is a devops and gaming enthusiast
on:
    push:
        branches-ignore:
            - ga-ignore-*
    pull_request:
        branches-ignore:
            - ga-ignore-*
    
env:
  EXECUTABLES: 202unsold
  MIRROR_URL: https://github.com/HKafuiEPI/choco_source
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: coding_style
        uses: actions/checkout@v4
      - run: |
             check.sh $(pwd) $(pwd)
             if [ -s coding-style-reports.log ];
             then
                cat coding-style-reports.log > $GITHUB_OUTPUT
                exit 1
             fi
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    timeout-minutes: 2
    needs: check_coding_style
    steps:
      - name: compiler
        uses: actions/checkout@v4
      - run: |
             make
             if [-f !$(EXECUTABLES)];
             then
                exit 1
             fi
      - name: cleaner
        uses: actions/checkout@v4
      - run: make clean
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    timeout-minutes: 2
    needs: check_program_compilation
    steps:
      - name: tester
        uses: actions/checkout@v4
      - run: make tests_run