name: Chocolatine Workflow

on:
  push:
    branches:
      - '*'
      - '!ga-ignore-*'
  pull_request:
    branches:
      - '*'

env:
  MIRROR_URL: 
  EXECUTABLES: 

jobs:
  check_coding_style:
    name: Check Coding Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Coding Style Checker
        run: docker run --rm -v $(pwd):/workspace ghcr.io/epitech/coding-style-checker:latest check.sh $(pwd) $(pwd)

      - name: Display Coding Style Errors
        run: |
          input="coding-style-reports.log"
          if [ - s "coding-style-reports.log"]; then
            while IFS= read -r -a line; do
              IFS=':' read -ra ligne <<< "$line"
              echo "::error title=${ligne[2]#./} coding style error,file=${ligne[0]},line=${ligne[1]}::${ligne[3]}"
            done < "$input"
            exit 1
          fi

  check_program_compilation:
    name: Checking Program Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Launch Make
        run: make

      - name: Clean Build
        run: make clean

      - name: Verify Executables
        run: |
          for exe in $(echo $EXECUTABLES | tr "," "\n"); do
            if [ ! -x "$exe" ]; then
              echo "$exe does not exist or is not executable"
              exit 1
            fi
          done
