name: CHOCOLATINE

on: [ push, pull_request ]

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - name: coding_style_checker
        run: check.sh $(pwd) $(pwd)