name: Chocolatine Workflow

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_coding_style:
    name: Check Coding Style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1
      - name: Launch of the coding style
        run: check.sh $(pwd) $(pwd)
      - name: Verify coding-style errors
        run: |
          if [ -s coding-style-reports.log ]; then
            while read -r line; do
              echo "::error file=${{ github.event.pull_request.head.sha }}::${line}"
            done < coding-style-reports.log
            exit 1
          fi

  check_program_compilation:
    name: Check Program Compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    needs: check_coding_style
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch of compilation
        run: timeout 120 make
      - name: Verify executable
        run: |
          if [[ ! -x "$exe" ]]; then
            echo "::error file=${exe}::Executable not found"
            exit 1
          fi
      - name: Clean object files
        run: make clean
      - name: Clean repo
        run: make fclean

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    needs: check_program_compilation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch unit-tests
        run: timeout 120 make tests_run