name: Chocolatine

on:
    push:
        branches-ignore:
            - ga-ignore-*
    pull_request:
        branches-ignore:
            - ga-ignore-*

env:
  MIRROR_URL: git@github.com:youyouAmd007/mirror_repo.git
  EXECUTABLES: my_ls 

jobs:
  check_coding_style:
    name: Checking the coding style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Check and run coding style
        uses: actions/checkout@v4
      - run: |
             check.sh $(pwd) $(pwd)
             if [ -s coding-style-reports.log ];
             then
                cat coding-style-reports.log
                exit 1
             fi

  check_program_compilation:
    name: Checking that the program compiles correctly
    runs-on: ubuntu-latest
    needs: check_coding_style
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - name: Make run
        uses: actions/checkout@v4
      - run: |
             make
             if [ -f !$EXECUTABLES ];
             then
                exit 1
             fi
      - name: Make clean run
        uses: actions/checkout@v4
      - run: make clean

  run_tests:
    name: Run the units_test
    runs-on: ubuntu-latest
    needs: check_program_compilation
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - name: Make tests
        uses: actions/checkout@v4
      - run: make tests_run
