name: Chocolatine
on:
  push:
    branches-ignore:
      - ga-ignore-*
  pull_request:
    branches-ignore:
      - ga-ignore-*
env:
  MIRROR_URL: "git@github.com:mhdadn04/chocolatin.git"
  EXECUTABLES: "202unsold"

jobs:
  checking_the_coding_style:
    name: Check the coding style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: check the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: run coding style
        run: check.sh $(pwd) $(pwd)
      - name: report coding style checking
        if: failure()
        run: cat coding-style-reports.log && exit 1

  check_program_compilation:
    name: Check program compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    needs: checking_the_coding_style
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: program's compilation
        run: make
        timeout-minutes: 2
      - name: clean repository
        run: make clean
      - name: Verify binaries
        run: |
          IFS=','
          set -- $EXECUTABLES
          for i in "$@"; do
            if [ ! -x "$i" ]; then
              echo "Missing or non-executable file $i"
              exit 1
            fi
          done

  run_tests:
    name: run tests
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    needs: check_program_compilation
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: run tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    name: Push to mirror
    runs-on: ubuntu-latest
    needs: run_tests
    if: github.event_name == 'push'
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}