name: Chocolatine

on:
  push:
    branches-ignore:
     - ga-ignore-*
  pull_request:

env:
  MIRROR_URL: ${{ secrets.MIRROR_URL }}
  EXECUTABLES: "cesar"

jobs:
    check_coding_style:
      runs-on: ubuntu-latest
      steps:
        - name: step1
          uses: actions/checkout@v4
        - name: step2
          uses: docker://ghcr.io/epitech/coding-style-checker:latest
          with:
            args: check.sh $(pwd) $(pwd)
    check_program_compilation:
      name: Compilation
      runs-on: ubuntu-latest
      needs: check_coding_style
      container: epitechcontent/epitest-docker
      steps:
        - name: step1
          uses: actions/checkout@v4

        - name: step2
          run: timeout 120 make

        - name: step3
          run: |
           for file in $EXECUTABLES;do
            if [[!-x $file]];then

               exit 84
             fi
            done

        - name: step4
          run: make fclean

    run_tests:
      name: Run Tests
      runs-on: ubuntu-latest
      needs: check_program_compilation
      container: epitechcontent/epitest-docker
      steps:
       - name: step1
         uses: actions/checkout@v4

       - name: step2
         run: timeout 120 make tests_run