env:
  MIRROR_URL: git@github.com:EpitechPromo2028/B-CPE-210-COT-2-1-solostumper03-juao.aifa.git
  EXECUTABLES: fazzbizz

name: chocolatine
on: 
  push:
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - run: check.sh $(pwd) $(pwd)
      - run: |
          CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
          for ERRORS in $CODING_STYLE_ERRORS; do
            array=(`echo $ERRORS | sed 's/:/\n/g'`)
            echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
          done
          if [[ -n $CODING_STYLE_ERRORS ]]
          then
            exit 1
          else
            echo No coding style errors detected
          fi
  check_program_compilation:
    needs: check_coding_style
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - run: make
        timeout-minutes: 2
      - run: make clean
      - run: |
          for i in "${EXECUTABLES}"; do
            if [[ ! -x "$i" ]]; then
              exit 1
            fi
          done