name: Chocolatine Workflow
on:
  push:
    branches-ignore:
      - ga-ignore-*
  pull_request:
    branches-ignore:
      - ga-ignore-*
env:
    MIRROR_URL: git@github.com:EpitechPromo2029/B-DOP-200-COT-2-1-chocolatine-abiola.philippe.git
    EXECUTABLES: mini_printf

jobs:
  check_coding_style:
    name: coding style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run coding style checker
        id: coding_style
        run: check.sh $(pwd) $(pwd)
  check_program_compilation:
    name: program compilation
    needs: check_coding_style
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: repository
        uses: actions/checkout@v4
      - name: Make
        run: make
        timeout-minutes: 2
      - name: Make fclean
        run: make clean
      - name: executable progam
        run: |
           if [ -f mini_printf ]; then
             if [ ! -x mini_printf ]; then
               exit 1
             fi
           else
             exit 1
           fi

  run_tests:
    name: tests runing
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tests
        timeout-minutes: 2
        run: make tests_run
  push_to_mirror:
    name: Push to mirror repository
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target-repo-url: ${{ env.MIRROR_URL }}
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
