name: my_chocol
on: 
  push:
  branches-ignore:
    - 'ga-ignor-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
    
  env:
    MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-1-chocolatine-eben-ezer.klobo.git"
    EXECUTABLES: "my_sokoban"
jobs:
    check_coding_style:
    run-on: ubuntu-latest
    image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      run: check.sh $(pwd) $(pwd)
    - if [ -f coding-style-reports.log ]; then while IFS= read -r ligne; do
        fichier=$(echo "$ligne" | cut -d':' -f1);
        numero_ligne=$(echo "$ligne" | cut -d':' -f2);
        message_erreur=$(echo "$ligne" | cut -d':' -f3-);
        echo "::error file=$fichier,line=$numero_ligne::Erreur de style de codage : $message_erreur";
      done < coding-style-reports.log;
    ficodage
  allow_failure: false

  check_coding_style:
  run-on: ubuntu-latest
  image: ghcr.io/epitech/coding-style-checker:latest
  steps:
    - check.sh $(pwd) $(pwd)
    - if [ -f coding-style-reports.log ]; then while IFS= read -r ligne; do
        fichier=$(echo "$ligne" | cut -d':' -f1);
        numero_ligne=$(echo "$ligne" | cut -d':' -f2);
        message_erreur=$(echo "$ligne" | cut -d':' -f3-);
        echo "::error file=$fichier,line=$numero_ligne::Erreur de style de codage : $message_erreur";
      done < coding-style-reports.log;
    fi
  allow_failure: false

  run_tests:
  run-on: ubuntu-latest
  image: epitechcontent/epitest-docker
  steps:
3


    - timeout 2m make tests_run

  push_to_mirror:
  run-on: ubuntu-latest
  image: alpine/git
  steps:
    - mkdir -p ~/.ssh/
    - echo "$GIT_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $(echo $MIRROR_URL | awk -F[@/] '{print $3}') >> ~/.ssh/known_hosts
    - git remote add mirror $MIRROR_URL
    - git push --mirror mirror
  only:
    - push